### ISSUE TITLE
Diagnostic does not recognize "@junit//java" as valid dependency 

### ISSUE THREAD

**Issue by jasonxris** [BYU-Bazel/bazel-ls#116]
The IntelliJ Bazel plugin marks Junit as a dependency using the syntax "@junit//java" 

Currently the diagnostics  thinks that @junit//java does not exist
![image](https://user-images.githubusercontent.com/55801252/109586601-bdb60980-7ac2-11eb-94ae-4e7bd11f5a41.png)

**Comment by josiahsrc** [comment]
We need to make it so the workspace tree queries external repos. Currently the diagnostics are ignoring external repos.

**Comment by josiahsrc** [comment]
All external workspaces are treated as valid. This is to keep things simple.
