### ISSUE TITLE
Parser creates incorrect path for Source files 

### ISSUE THREAD

**Issue by jasonxris** [BYU-Bazel/bazel-ls#134]
With the IntelliJ Plugin repo, source files are being incorrected created

Here is a log of the creation of a few of the source files 
```
00:53:21.983 [pool-2-thread-1] INFO  server.bazel.cli.Bazel - source file //base:src/com/google/idea/blaze/base/ideinfo/ProjectDataInterner.java

00:53:21.983 [pool-2-thread-1] INFO  server.bazel.cli.Bazel - source file //base:src/com/google/idea/blaze/base/ideinfo/ProtoWrapper.java
```

All source files found in the baze package are given the value
//base:path/to/file.java
instead of 
//base/path/to/file

This causes it to be identified as a non-existing source file
![image](https://user-images.githubusercontent.com/55801252/110876014-ea70da80-8293-11eb-8dba-bdce928fa3fc.png)

The diagnostic works when the incorrect path is placed
![image](https://user-images.githubusercontent.com/55801252/110876108-1d1ad300-8294-11eb-9e66-9a7ddc7446dd.png)

However i think this will fail to build since "//base:src/com/google/idea/blaze/base/ideinfo/ProjectDataInterner.java" is an invalid path to a file

**Comment by jasonxris** [comment]
I believe this might be caused by the intellij project structure and the method used to parse the information into the workspace tree

The ONLY build file is found at the top of the baze package. Sources are found in other packages within the base package.
![image](https://user-images.githubusercontent.com/55801252/110876562-f8732b00-8294-11eb-98de-24e8d3565b5b.png)

**Comment by jasonxris** [comment]
Relative paths work if you put : in front of the path
This should help with debugging the parse

![image](https://user-images.githubusercontent.com/55801252/110877173-39b80a80-8296-11eb-81eb-086cf382f051.png)

**Comment by josiahsrc** [comment]
> However this will definitely fail to build since "//base:src/com/google/idea/blaze/base/ideinfo/ProjectDataInterner.java" is an invalid path to a file

Is there a BUILD file in the `//base` directory? If so, I think this will actually work. In Jared's project there ere paths that look like this:

`//path/to:more/paths/beneath/this/to/src/file.java`

**Comment by jasonxris** [comment]
@josiahsrc 
There is a BUILD file there. 

If that is the case, then we just need to be able to support formats. 

":relative/path/to/file.java"
And
"relative/path/to/file.java"

Both are valid. 
However since the bazel query actually outputs the file location as:
` //base:src/com/google/idea/blaze/base/ideinfo/ProjectDataInterner.java`
We currently only support the` :/src/to/file.java` format

It looks like bazel query replaces the first / with : if the source file is contained outside of a BUILD package

**Comment by josiahsrc** [comment]
Have you tested this one? 

"relative/path/to/file.java"

I remember that not working for some reason

**Comment by jasonxris** [comment]
"relative/path/to/file.java"

Will not currently work for that project 

This is because the workspace tree is storing the package names as 
[ ":relative", "path", "to" ] 

So the package "relative" doesn't exist on the tree 

I think that the ":" should be removed when parsing the bazel query into the workspace tree 

Not sure what the best way of verifying a source file that uses ":" in the path. 

I think there are 2 cases to look for 
1 
":relative/path/file.Java" 

2 
"//root/package:relative/path/file.java"

**Comment by josiahsrc** [comment]
Jaren and I created a "Label" class which could handle this. It is well tested. Usage:

```
Label.parse("@bazel//string/with:label/syntax/stuff.java")
```

This will parse the label and convert into java objects that are easier to work with

**Comment by josiahsrc** [comment]
I'm doing further tests on this. Notes:

## 

- You can't depend on a file that is part of another package: 
![image](https://user-images.githubusercontent.com/37915005/110958099-90126100-8309-11eb-912b-0ec2edeedac1.png)

- You may not depend on a sub package without the `//` symbols
![image](https://user-images.githubusercontent.com/37915005/110958267-c51eb380-8309-11eb-8617-2a86de4761a4.png)

- You may depend on a package's file directly, but you must acknowledge the existence of the package with the `:` symbol
![image](https://user-images.githubusercontent.com/37915005/110958472-f5fee880-8309-11eb-884b-d20d8c63e3b2.png)

- You may duplicate imports of files that belong to the same package
![image](https://user-images.githubusercontent.com/37915005/110958663-2d6d9500-830a-11eb-841a-825208f8c38d.png)

- You may not contain two instances of the exact same label within a label
![image](https://user-images.githubusercontent.com/37915005/110958857-5d1c9d00-830a-11eb-857c-833b10c3cd0a.png)

- You may reference a file in your current package with or without the ":" symbol, as Jason mentioned above ^^
![image](https://user-images.githubusercontent.com/37915005/110959265-bedd0700-830a-11eb-8553-8c4ed1c4abae.png)

- You may not reference source files in the deps attributes
![image](https://user-images.githubusercontent.com/37915005/110959620-1ed3ad80-830b-11eb-8a99-72aa38a62e07.png)

# Implementation Notes

- `@` indicates the presence of a workspace
- `//` indicates the presence of a root level reference
- `:` indicates the presence of a package level reference

**Comment by josiahsrc** [comment]
@jasonxris I think this is fixed up (at least as far as parsing goes, I didn't touch the workspace tree). Would you mind trying this out on your machine? Branch is here: https://github.com/BYU-Bazel/bazel-ls/tree/fix-parser-paths-134
