### ISSUE TITLE
Formatter can not format BUILD.bazel files

### ISSUE THREAD

**Issue by jasonxris** [BYU-Bazel/bazel-ls#162]
22:59:48.451 [pool-2-thread-1] INFO  server.formatting.FormattingProvider - Invoked FormattingProvider
22:59:48.452 [pool-2-thread-1] INFO  server.formatting.FormattingProvider - Could not format this type of file: BUILD.bazel

I'm pretty sure that BUILD.bazel files are how Jared has his BUILD files marked. 
Currently The formatter service does not support this type of file extension. 

I'm not sure if this is a restriction that Buildifier puts in or a restriction we give it in the provider. 

Should be easy to check for support BUILD extensions and possibly editing the fioe name before inputting it to the Buildifer to make it work.

**Comment by loganmcbride148** [comment]
Ha ha I know exactly what's wrong. We wrote it to handle .bzl but not .bazel. This will be an easy fix.
