### ISSUE TITLE
Assess and make plan for syntax highlighting

### ISSUE THREAD

**Issue by NovaMachina** [BYU-Bazel/bazel-ls#34]

**Comment by josiahsrc** [comment]
Findings:
- [A syntax server for java built in java](https://github.com/eclipse/eclipse.jdt.ls/tree/master/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/syntaxserver)
- [Vague but helpful steps for adding in syntaxes into a java project](https://www.eclipsecon.org/europe2017/session/language-edition-support-eclipse-ide-best-breed-generic-editor-language-servers-and-textmate)
- [LSP docs for syntax highlighting](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentHighlight)

Uh oh:

[LSP doesn't support syntax highlighting](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019)

> TextMate grammar files
> The LSP does not include specification on how to provide text colorization for languages. To provide custom colorization for languages in Visual Studio, extension developers can use a TextMate grammar file. To add custom TextMate grammar or theme files, follow these steps...

Solutions:
- Use already existing LSP syntax for bazel and don't put in the server
- Curl the file down into the client
- Provide the syntax in the server, but leave it up to the client to implement <-- I like this one

## BUT WAIT

This [link](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) suggests that you can do syntax highlighting using semantic token providers

**Comment by josiahsrc** [comment]
Syntax highlighting will be tracked on https://github.com/lucidsoftware/vscode-bazel/issues/37

**Comment by josiahsrc** [comment]
Syntax highlighting will be tracked on https://github.com/lucidsoftware/vscode-bazel/issues/37
