### ISSUE TITLE
Implement syntax highlighting

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#37]
Bring syntax highlighting back into the client using the existing text-mate grammars

**Comment by josiahsrc** [comment]
This issue has a lot of info on language server syntax highlighting https://github.com/lucidsoftware/vscode-bazel/issues/34#issuecomment-720588535

**Comment by josiahsrc** [comment]
Bumping up to 8 story points because method 1 of doing this task is still research oriented, which will take more time

**Comment by jasonxris** [comment]
Previous implementation is working
