### ISSUE TITLE
Provide syntax highlighting from the server

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#39]
The syntax highlighting is currently provided on the client. Is there a way to provide it from the server?

Use either
1. [This method](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) which suggests that you can do syntax highlighting using semantic token providers
2. TextMate grammar on the client

Use the textmate solution if the first option doesn't work. With the text mate solution, maybe find a way to provide the language syntax from the server, rather than directly copying/pasting it into the client.

**Comment by jasonxris** [comment]
https://code.visualstudio.com/api/references/vscode-api#DocumentSemanticTokensProvider

Server provided tokenization can allow the language server to extend the client side syntax highlighting. 

This allows Syntax highlighting to be done intelligently in relation to the whole project. 
For example, a constant variable name can be rendered using constant highlighting throughout the project, not just at the place of its declaration.

 Semantic highlighting goes on top of the syntax highlighting

https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide

**Comment by josiahsrc** [comment]
Semantic highlighting is needed, it's fine to leave the base syntax highlighting on the client.
