### ISSUE TITLE
Create some example bazel projects

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#41]
Put some example bazel projects in the examples folder

- [ ] Create 1 or 2 typescript example projects (Ben)
- [x] Create nice big juicy example (Josiah)
- [x] Create small example (Josiah)

**Comment by josiahsrc** [comment]
@benocarlson I created the `/examples` folder before, I'm going to be placing my example projects in subdirectories of that folder

**Comment by benocarlson** [comment]
> @benocarlson I created the `/examples` folder before, I'm going to be placing my example projects in subdirectories of that folder

@josiahsrc I'll do the same

**Comment by josiahsrc** [comment]
@benocarlson You're creating a typescript example for this sprint, is that right?
