### ISSUE TITLE
As a developer, I want to be able to run test cases using codelense

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#9]
Be able to run tests using codelense.

- [ ] A codelense word should appear above test related items, such as bazel test rules and source code test files.
- [ ] Clicking on these code lenses should start up bazel in test mode.
- [ ] Write test cases.

**Comment by loganmcbride148** [comment]
I haven't found a good example project with tests to use to test this functionality. Does anyone know of one, or is comfortable enough with Bazel that they could write a small one?

**Comment by josiahsrc** [comment]
@loganmcbride148 @benocarlson Here is a small example, hope this helps: https://github.com/BYU-Bazel/bazel-ls/pull/160/files
