### ISSUE TITLE
Cache Analysis Bazel Workspace File Systems

### ISSUE THREAD

**Issue by josiahsrc** [BYU-Bazel/bazel-ls#94]
The Bazel invoker created from #81 will help us understand how our client's Bazel projects are laid out. This is great, but the Bazel invoker takes a long time to complete. We need to cache our client's file system so we don't hang for so long.

Use the Bazel invoker to construct a WorkspaceTree, which is created from in #91. Cache the workspace tree after each Bazel query to save on performance.

- [x] Use the bazel invoker to interpret a client's bazel file system.
- [x] Initialize the analyzer on extension start. This should cache a representation of our user's file system as a `WorkspaceTree`
- [ ] Whenever appropriate, or possibly on `didUpdate` from the `BazelServices`, update the cached workspace stored in the analyzer. Only update what needs to be updated.

Unit tests
- [x] Create unit tests to test this behavior

**Comment by josiahsrc** [comment]
More context found in #82

**Comment by NovaMachina** [comment]
`Whenever appropriate, or possibly on didUpdate from the BazelServices, update the cached workspace stored in the analyzer. Only update what needs to be updated.`

Not sure how to do this one quite yet. Still working on it.
